
# Makefile for compiling raspberry compatible
spi_test : main.c
		gcc -Wall -g main.c -lzmq -o spitest -lpthread -pthread -lpigpio
		#gcc -Wall -g main.c -lzmq -o spitest -lpigpio -lpthread -pthread
